name: StaffLog
version: 1.0
main: byron.StaffLog.StaffLog
commands:
    s:
      description: Default staffchat command
      usage: /s
      permission: stafflog.chat
    commandblock:
      description: Gives the player a command block.
      usage: /commandblock
      permission: StaffLog.give